---
title: "Task Three: Data"
author: "Tamrn Baxter"
date: "2022-09-01"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
##Load required packages
library(tidyverse)
library(dplyr)
```


```{r}
##TASK 3

#Dataset 1
#Our first data comes from R (It is inbuilt)
##Load any pre-loaded data in R
data(msleep)
```

```{r}
##Let's do some analysis on the msleep dataset
##Check the number of observations
dim(msleep)
```

```{r}
##Check the structure of the data, that is, check the datatypes
str(msleep)
```
##As evident, we can see the datatypes of the variables, for instance, the name, genus, and vore are all categorical variables while the rest are numerical variables. Sleep_total, awake, brainnt, and bodywt are quantitative while sleep_cycle is qualitative in nature.

```{r}
##Do some descriptive statistics of the data (this is its description in terms of statistical variables)
summary(msleep)
##The summary statistics shows the mean, max, min, 1st and 3rd quartiles of the data.
```

```{r}
##Dataset 2

#The second dataset we will be exploring is made available on <https://www.kaggle.com/>
##Import the first dataset
Loan_default_Data<- read.csv("Loan_Default.csv")
```

```{r}
##Check the number of observations
dim(Loan_default_Data)
```

```{r}
##Check the structure of the data (Check datatypes)
str(Loan_default_Data)
```

```{r}
##Do descriptive statistics of the data
summary(Loan_default_Data)
```

```{r}
##Dataset 3
#The third dataset we will be exploring is also made available on <https://www.kaggle.com/>
##Import the dataset
SalaryInfor<- read.csv("salary.csv")
```

```{r}
##Check the number of observations
dim(SalaryInfor)
```

```{r}
##Check the dataset datatypes
str(SalaryInfor)
```

```{r}
##Descriptive statistics of the data
summary(SalaryInfor)
```