---
title: "TASK12: Time-series Practical"
author: "Tamryn Baxter"
date: "2022-09-01"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
##TASK 12 . Time-Series Practical
##Load the AirPassengers dataset that is inbuilt in R
data("AirPassengers")
```

```{r}
##Assign it to an object
Air.ts<- AirPassengers
```

```{r}
##Explore the dataset
##Check the class for the data
class(Air.ts)
```

```{r}
##Structure
str(Air.ts)
```

```{r}
##First few rows
start(Air.ts)
```

```{r}
##Last few rows
end(Air.ts)
```

```{r}
##Frequency
frequency(Air.ts)
```

```{r}
##Check the summary of the data
summary(Air.ts)
```

```{r}
##Now, plot the time series
library(tseries)
plot(Air.ts, ylab= "Air Passengers (\'000s)", lwd= 2)
```

```{r}
##Create the AutoCorrelation plot
acf(Air.ts)
```

```{r}
##Autoregressive model
adf.test(Air.ts, k= 12)
```

```{r}
##Conduct the PACF
pacf(Air.ts)
```
##Evaluation
#The best model to use in this task is the autoregressive model since it allows us to also see the p-value and the statistical results.




